export const strings = {
  LOGIN: "Login",
  LOGOUT: "Logout",
  E_COMMERCE: "E-commerce Website",
  SHOP: "Shop",
  CART: "Cart",
  WISHLIST: "Wishlist",
  EMPTY_CART: "Your Shopping Cart is Empty",
  CHECKOUT: "Checkout",
  YOUR_ITEMS: "Your Cart Items",
  CONTINUE_SHOPPING: "Continue Shopping",
  TOTAL: "Total: ₹",
  PRICE: "Price: ₹",
  ORDER_SUMMARY: "Order Summary",
  DELIVERY_INFO: "Delivery Information",
  FULL_NAME: "Full Name:",
  ADDRESS: "Address:",
  CITY: "City:",
  ZIP: "ZIP Code:",
  COUNTRY: "Country:",
  USE_LOCATION: "Use Current Location",
  PLACE_ORDER: "Place Order",
  GO_TO_CART: "Go To Cart",
  ADD_TO_CART: "Add To Cart",
  GO_TO_WISH: "Go To Wishlist",
  ADD_TO_WISH: "Add To Wishlist",
  YOUR_WISH_ITEMS: "Your Wishlist Items",
  EMPTY_WISH: "Your Shopping Wishlist is Empty",
};
